channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6.7
  - pandas=1.0.4
  - tqdm=4.46.0
  - numpy=1.18.4
  - snakemake-minimal=5.4.5=py_0
  - pyarrow=0.15.1
  - scipy=1.4.1
  - statsmodels=0.11.1
  - r-base=4.0.2
  - r-data.table=1.14.0
  - r-rfast=2.0.3
